### ISSUE TITLE
Phonegap Build rejects app

### ISSUE THREAD

**Issue by jamminjames** [appfeel/tappx-phonegap#1]
In your instructions you say:

`Add the following tag to your config.xml file to show Tappx ads with your Phonegap Build apps:
<gap:plugin name="com.ads.tappx" source="plugins.cordova.io" version="2.0.14"/>
Please note to use version 2.0.14 as Phonegap Build is still not supporting cordova android@4.0.0.`

However, Phonegap Build is rejecting it. The error says:
Error - Plugin (or a specific plugin version) not found in external repo: com.ads.tappx

**Comment by appfeel** [comment]
We have moved the plugin to npm, you can now use:

``` xml
<gap:plugin name="cordova-admob" source="npm"/>
```

Please, could you check it's working?
