### ISSUE TITLE
Wrong options key on manual (tappxIdiOs -> tappxIdiOS)

### ISSUE THREAD

**Issue by cassioscofield** [appfeel/tappx-phonegap#4]
Hi, in the wiki page (https://github.com/appfeel/tappx-phonegap/wiki), the tappx key of the options in with the wrong case for apple devices, which makes the ads not work, I lost quite some time in this, please fix so other people don`t have this problem. Thanks for the great plugin.

tappxIdiOs -> tappxIdiOS 

in

tappx.createBannerView({
      publisherId:    "NONE",
      tappxIdiOs:     "/XXXXXXXXX/Pub-XXXX-iOS-IIII",
      tappxIdAndroid: "/XXXXXXXXX/Pub-XXXX-Android-AAAA",
      tappxShare:     1
    });

**Comment by miqmago** [comment]
Thanks, that waas already fixed few months ago :)
