### ISSUE TITLE
Do I need to install tappx-phonegap with cordova-admob plugin?

### ISSUE THREAD

**Issue by hasan-araav** [appfeel/tappx-phonegap#5]
I already installed the cordova-admob plugin by appfeel. Now I want to integrate the tappx. Do I need to install the tappx-phogap plugin also.

**Comment by miqmago** [comment]
No, you just can use the `cordova-admob` plugin, see here: https://github.com/appfeel/admob-google-cordova/wiki/Tappx-configuration
